#!/usr/bin/env bash
# Copyright 2026 The Virgil Language Server Authors.
# SPDX-License-Identifier: Apache-2.0
#
# Generate BuildInfo.v3 with the server version and exact source revisions.
# Usage: gen-buildinfo.sh <output-file>
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
VIRGIL=${VIRGIL:-$ROOT/vendor/virgil}
OUT=$1

version=$(tr -d '[:space:]' < "$ROOT/VERSION")
revision=$(git -C "$ROOT" describe --always --dirty --abbrev=12 2>/dev/null || echo unknown)
virgil_revision=$(git -C "$VIRGIL" rev-parse HEAD 2>/dev/null || echo unknown)

tmp=$(mktemp)
cat > "$tmp" <<V3
// Generated by scripts/gen-buildinfo.sh; do not edit.
component BuildInfo {
	def NAME = "virgil-lsp";
	def VERSION = "$version";
	def REVISION = "$revision";
	def VIRGIL_REVISION = "$virgil_revision";
}
V3
# Only touch the output when it changes, to avoid needless rebuilds.
if cmp -s "$tmp" "$OUT" 2>/dev/null; then rm -f "$tmp"; else mv "$tmp" "$OUT"; fi
